name: Steam Sales Bot

on:
  schedule:
    - cron: '*/30 * * * *' # Автозапуск каждые 30 минут
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Принудительная очистка канала'
        required: false
        default: 'false'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Клонируем репозиторий
      uses: actions/checkout@v3

    - name: Устанавливаем Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Устанавливаем библиотеки
      run: pip install requests

    - name: Запускаем проверку цен и пульт
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        ADMIN_TELEGRAM_ID: ${{ secrets.ADMIN_TELEGRAM_ID }}
        PERSONAL_GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
        FORCE_UPDATE: ${{ github.event.inputs.force_update }}
      run: python main.py

    - name: Сохраняем историю и сайт на GitHub
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add index.html history.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "🌐 Синхронизация базы и сайта" && git push)
